I = imread('1.8.jpg');
[x,map]=rgb2ind(I,128);
imshow(x,map);
maphsv=rgb2hsv(map);
[H,S,V]=ind2rgb(x,maphsv);
figure(1);subplot(1,4,1);imshow(x,map);title('image couleur');
subplot(1,4,2);imshow(H);title('H');
subplot(1,4,3);imshow(S);title('S');
subplot(1,4,4);imshow(V);title('V');
HSV(:,:,1)=H;
HSV(:,:,2)=S;
HSV(:,:,3)=V;
figure,imshow(HSV);
